 github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
remote_theme: daviddarnes/alembic
 gfm_quirks: paragraph_end
plugins:
  - jekyll-remote-theme